#!/bin/bash

for file in `find . -regex '\./.*\.d\.ts' -not -path './node_modules/*'`; do
  sed -i '' -E "1s/([0-9]{1,}\.?){1,}/$1/" $file
  echo "updated: $file"
done

npm version $1 --no-git-tag-version --allow-same-version > /dev/null
echo "updated: package.json"
